"""Helpers to query the bundled Vietnamese administrative reference data.

Data source: features/account/static_data/vn_provinces.json
Generated by: scripts/seed_vn_provinces.py
"""
import json
import os
from functools import lru_cache
from typing import Optional


_HERE = os.path.dirname(os.path.abspath(__file__))
_DATA_PATH = os.path.join(_HERE, 'vn_provinces.json')


@lru_cache(maxsize=1)
def _load() -> dict:
    with open(_DATA_PATH, encoding='utf-8') as f:
        return json.load(f)


def get_province(code: int) -> Optional[dict]:
    for p in _load()['provinces']:
        if p['code'] == code:
            return p
    return None


def get_ward(province_code: int, ward_code: int) -> Optional[dict]:
    p = get_province(province_code)
    if not p:
        return None
    for w in p.get('wards', []):
        if w['code'] == ward_code:
            return w
    return None


def list_provinces() -> list[dict]:
    return [
        {'code': p['code'], 'name': p['name']}
        for p in _load()['provinces']
    ]


def list_wards(province_code: int) -> list[dict]:
    p = get_province(province_code)
    if not p:
        return []
    return [{'code': w['code'], 'name': w['name']} for w in p.get('wards', [])]


def version() -> str:
    return _load().get('version', 'unknown')
