"""
Django settings for LMS_SYSTEM project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-=ml)-2up77okb726(@7r&s_3rzx0pn0(o3+gob1pzo_3wr6v3p')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'django_filters',
    'django_cassandra_engine',
    'corsheaders',

    # Local apps
    'core',
    'features.account',
    'features.course.classroom',
    'features.course.exam',
    'features.sharing',
    'features.resource',
    'features.chat',
    'features.course.meeting_room',
    'features.quiz',
    'features.notification',
    'features.calendar',
    'features.payment',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'core.backend.auth.jwt_auth.CassandraJWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),
    'EXCEPTION_HANDLER': 'core.backend.exceptions.global_exception_handler',
}

from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'uid',
    'USER_ID_CLAIM': 'user_id',
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'LMS_SYSTEM.urls'

ASGI_APPLICATION = 'LMS_SYSTEM.asgi.application'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    },
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LMS_SYSTEM.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# noinspection PyUnresolvedReferences
from core.configs.database import DATABASES as CASSANDRA_DATABASES

DATABASES = {
    'sqlite': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Merge Cassandra config as default
DATABASES.update(CASSANDRA_DATABASES)



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# CORS configuration
CORS_ALLOW_ALL_ORIGINS = True

CASSANDRA_FALLBACK_ORDER_BY_PYTHON = True

# Google OAuth
GOOGLE_CLIENT_ID = config('GOOGLE_CLIENT_ID', default='')
GOOGLE_CLIENT_SECRET = config('GOOGLE_CLIENT_SECRET', default='')
GOOGLE_CONSUMER_REDIRECT_URI = config(
    'GOOGLE_CONSUMER_REDIRECT_URI',
    default='http://localhost:8000/api/v1/consumer/account/auth/google/callback/'
)
GOOGLE_SPACE_REDIRECT_URI = config(
    'GOOGLE_SPACE_REDIRECT_URI',
    default='http://localhost:8000/api/v1/space/account/auth/google/callback/'
)
FRONTEND_CONSUMER_URL = config('FRONTEND_CONSUMER_URL', default='http://localhost:3000')
FRONTEND_SPACE_URL = config('FRONTEND_SPACE_URL', default='http://localhost:3003')
GOOGLE_AUTH_URL = config('GOOGLE_AUTH_URL', default='https://accounts.google.com/o/oauth2/v2/auth')
GOOGLE_TOKEN_URL = config('GOOGLE_TOKEN_URL', default='https://oauth2.googleapis.com/token')

# Email Settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='')

# MoMo Payment (sandbox)
MOMO_PARTNER_CODE = config('MOMO_PARTNER_CODE', default='MOMO')
MOMO_ACCESS_KEY = config('MOMO_ACCESS_KEY', default='F8BBA842ECF85')
MOMO_SECRET_KEY = config('MOMO_SECRET_KEY', default='K951B6PE1waDMi640xX08PD3vg6EkVlz')
MOMO_ENDPOINT = config('MOMO_ENDPOINT', default='https://test-payment.momo.vn/v2/gateway/api/create')
MOMO_REDIRECT_URL = config('MOMO_REDIRECT_URL', default='http://localhost:3000/payment/result')
MOMO_IPN_URL = config('MOMO_IPN_URL', default='http://localhost:8000/api/v1/consumer/payment/ipn/')
