EXAM_PERIOD_REGULAR = 'regular'
EXAM_PERIOD_MIDTERM = 'midterm'
EXAM_PERIOD_FINAL = 'final'

EXAM_PERIODS = (
    EXAM_PERIOD_REGULAR,
    EXAM_PERIOD_MIDTERM,
    EXAM_PERIOD_FINAL,
)

EXAM_PERIOD_TO_FOLDER_NAME = {
    EXAM_PERIOD_REGULAR: 'Thường xuyên',
    EXAM_PERIOD_MIDTERM: 'Giữa kỳ',
    EXAM_PERIOD_FINAL: 'Cuối kỳ',
}

FOLDER_NAME_TO_EXAM_PERIOD = {v: k for k, v in EXAM_PERIOD_TO_FOLDER_NAME.items()}

EXAM_ROOT_FOLDER_NAME = 'Bài kiểm tra'
DOCS_ROOT_FOLDER_NAME = 'Docs'
PREVIEW_ROOT_FOLDER_NAME = 'Preview'

EXAM_SUBFOLDER_NAMES = (
    EXAM_PERIOD_TO_FOLDER_NAME[EXAM_PERIOD_REGULAR],
    EXAM_PERIOD_TO_FOLDER_NAME[EXAM_PERIOD_MIDTERM],
    EXAM_PERIOD_TO_FOLDER_NAME[EXAM_PERIOD_FINAL],
)
